# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx/constraint_lab01.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sc1_0_0/design_1_sc1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sc1_0_0 || ORIG_REF_NAME==design_1_sc1_0_0} -quiet] -quiet

# XDC: d:/FACULTATE/ANUL_III/SEM_I/CN2/xilinx/prb1_c1-vivado/prb1_c1-vivado.gen/sources_1/bd/design_1/design_1_ooc.xdc
