// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sc1_sc1,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.934000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=28,HLS_VERSION=2023_2}" *)

module sc1 (
        a,
        b,
        c,
        d,
        out1,
        out2
);


input  [0:0] a;
input  [0:0] b;
input  [0:0] c;
input  [0:0] d;
output  [0:0] out1;
output  [0:0] out2;

wire   [0:0] and_ln9_fu_86_p2;
wire   [0:0] xor_ln6_fu_80_p2;
wire   [0:0] xor_ln6_1_fu_92_p2;
wire   [0:0] var1_fu_74_p2;
wire   [0:0] xor_ln9_fu_104_p2;
wire   [0:0] or_ln12_fu_116_p2;
wire   [0:0] xor_ln12_fu_122_p2;
wire   [0:0] xor_ln12_1_fu_128_p2;
wire   [0:0] var3_fu_110_p2;
wire   [0:0] or_ln31_fu_140_p2;
wire   [0:0] var2_fu_98_p2;
wire   [0:0] var4_fu_134_p2;

assign and_ln9_fu_86_p2 = (d & c);

assign or_ln12_fu_116_p2 = (b | a);

assign or_ln31_fu_140_p2 = (var3_fu_110_p2 | var1_fu_74_p2);

assign var1_fu_74_p2 = (b & a);

assign var2_fu_98_p2 = (xor_ln6_fu_80_p2 & xor_ln6_1_fu_92_p2);

assign var3_fu_110_p2 = (xor_ln9_fu_104_p2 & and_ln9_fu_86_p2);

assign var4_fu_134_p2 = (xor_ln12_fu_122_p2 & xor_ln12_1_fu_128_p2);

assign xor_ln12_1_fu_128_p2 = (or_ln12_fu_116_p2 ^ 1'd1);

assign xor_ln12_fu_122_p2 = (d ^ c);

assign xor_ln6_1_fu_92_p2 = (1'd1 ^ and_ln9_fu_86_p2);

assign xor_ln6_fu_80_p2 = (b ^ a);

assign xor_ln9_fu_104_p2 = (var1_fu_74_p2 ^ 1'd1);

assign out1 = (var2_fu_98_p2 | or_ln31_fu_140_p2);

assign out2 = (var4_fu_134_p2 | var3_fu_110_p2);

endmodule //sc1
