-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sc1 is
port (
    a : IN STD_LOGIC_VECTOR (0 downto 0);
    b : IN STD_LOGIC_VECTOR (0 downto 0);
    c : IN STD_LOGIC_VECTOR (0 downto 0);
    d : IN STD_LOGIC_VECTOR (0 downto 0);
    out1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out2 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of sc1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sc1_sc1,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.934000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=28,HLS_VERSION=2023_2}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal and_ln9_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln6_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln6_1_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal var1_fu_74_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln9_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln12_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln12_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln12_1_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal var3_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln31_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal var2_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal var4_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    and_ln9_fu_86_p2 <= (d and c);
    or_ln12_fu_116_p2 <= (b or a);
    or_ln31_fu_140_p2 <= (var3_fu_110_p2 or var1_fu_74_p2);
    out1 <= (var2_fu_98_p2 or or_ln31_fu_140_p2);
    out2 <= (var4_fu_134_p2 or var3_fu_110_p2);
    var1_fu_74_p2 <= (b and a);
    var2_fu_98_p2 <= (xor_ln6_fu_80_p2 and xor_ln6_1_fu_92_p2);
    var3_fu_110_p2 <= (xor_ln9_fu_104_p2 and and_ln9_fu_86_p2);
    var4_fu_134_p2 <= (xor_ln12_fu_122_p2 and xor_ln12_1_fu_128_p2);
    xor_ln12_1_fu_128_p2 <= (or_ln12_fu_116_p2 xor ap_const_lv1_1);
    xor_ln12_fu_122_p2 <= (d xor c);
    xor_ln6_1_fu_92_p2 <= (ap_const_lv1_1 xor and_ln9_fu_86_p2);
    xor_ln6_fu_80_p2 <= (b xor a);
    xor_ln9_fu_104_p2 <= (var1_fu_74_p2 xor ap_const_lv1_1);
end behav;
